language: node_js
node_js:
  - "0.12"
  - "0.11"
  - "0.10"
  - "iojs"
  - "node"
install: npm i && npm i babel-polyfill
before_script: npm run-script build && tsd install
branches:
  only:
    - master
notifications:
  webhooks:
    on_success: change
    on_failure: always
    on_start: never