language: node_js
node_js:
  - "node"
install: npm i && npm i babel-polyfill
before_script: tsd install && npm run-script build 
branches:
  only:
    - master
notifications:
  webhooks:
    on_success: change
    on_failure: always
    on_start: never